version: "3.9"

services:
  stream-server:
    build: ./server
    container_name: stream-server
    ports:
      - "8001:8001"
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - stream-server
    restart: unless-stopped
